#!/usr/bin/env php
<?php
if (is_file(__DIR__ . '/../vendor/autoload.php')) {
    require __DIR__ . '/../vendor/autoload.php';
} else if (is_file(__DIR__ . '/../../../autoload.php')) {
    require __DIR__ . '/../../../autoload.php';
}

use Schedule\Cli;

$commander = new Commander();
$commander->name('schedule')
    ->version('0.1.0')
    ->command(
        array(
            'name' => 'init',
            'description' => 'Create an initial schedule.php file',
            'options' => Cli::options(),
            'callback' => function($input, $output) {
                Cli::init($input, $output);
            }
        )
    )
    ->run();